BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBBB BBBB
BB BBBB
XXXXX  XXXXXXXXX XXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX
        BBBBBBBBBB
        
    XXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
XXXXXXX
BBBBB
BBBBBBBB