# Generated by Django 2.2.7 on 2019-12-02 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Approved'), (2, 'Canselled'), (3, 'Finished')], default=0),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Worker'),
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Approved'), (2, 'Canselled')], default=0)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('work_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.WorkPlace')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Worker')),
            ],
        ),
    ]
