# Generated by Django 2.2.7 on 2019-12-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20191202_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Worker'),
        ),
    ]
