# Generated by Django 2.2.7 on 2019-12-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20191212_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='manager_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='worker_name',
            new_name='name',
        ),
    ]
